;
; SYSLIB Module Name:  SFWRITE
; Author:  Richard Conn
; SYSLIB Version Number:  3.6
; Module Version Number:  1.2

	public	f$write

;
;  F$WRITE -- WRITE BLOCK TO FILE WHOSE FCB IS PTED TO BY DE
;	RET W/A=0 IF OK AND FLAGS
;
	EXT	BDOS

F$WRITE:
	PUSH	HL	; SAVE HL
	PUSH	BC	; SAVE BC
	LD	C,B$RECW
	CALL	BDOS
	OR	A	; SET FLAGS (Z FLAG)
	POP	BC	; RESTORE BC
	POP	HL	; RESTORE HL
	RET

B$RECW	EQU	21	; WRITE RECORD

	END
