;
; SYSLIB Module Name:  SLCRLF
; Author:  Richard Conn
; SYSLIB Version Number:  3.6
; Module Version Number:  1.1

	public	lcrlf

;
;  LCRLF -- 
;	PRINT <CR> AND <LF> ON LST:
;	AFFECT NO REGS
;
	EXT	LOUT

LCRLF:
	PUSH	AF	; SAVE REG A AND FLAGS
	LD	A,CR	; PRINT <CR>
	CALL	LOUT
	LD	A,LF	; PRINT <LF>
	CALL	LOUT
	POP	AF	; RESTORE REG A AND FLAGS
	RET

;
;  ASCII SPECIAL CHARACTER EQUATES
;
NULL	EQU	 0	; NULL
BEL	EQU	 7	; BELL
BS	EQU	 8	; BACKSPACE
TAB	EQU	 9	; TAB
LF	EQU	10	; LINE FEED
CR	EQU	13	; CARRIAGE RETURN
CTRLR	EQU	'R'-40H	; CTRL-R
CTRLU	EQU	'U'-40H	; CTRL-U
CTRLX	EQU	'X'-40H	; CTRL-X
DEL	EQU	7FH	; DELETE CHAR

	END
