;
; LULIB Module: LUCLOSE
; Author: Richard Conn
; Date: 8 August 85
; LULIB Version: 1.0
; LULIB Module Version: 1.0
;
	public	luclose

;
;	LUCLOSE closes the file within a library which was opened by LUOPEN.
;
;	On input, DE = ptr to LUD
;

	.in	luddef

luclose:
	push	hl		; save regs
	push	bc
	push	af
	ld	hl,ludidx	; pt to index
	add	hl,de
	ld	b,4		; zero index and length
loop:
	ld	(hl),0		; store zero
	inc	hl		; pt to next
	djnz	loop
	pop	af		; restore regs
	pop	bc
	pop	hl
	ret

	end
