;
; SYSLIB Module Name:  SMHL4HC
; Author:  Richard Conn
; SYSLIB Version Number:  3.6
; Module Version Number:  1.1

	public	mhl4hc
;
;	MHL4HC -- Store HL as 4 Hex Characters in memory; on input, DE pts
; to 4-byte buffer and HL=value; on return, DE pts to byte after buffer
;	No Registers are to be affected.
;
	EXT	MA2HC	; STORE A AS 2 HEX CHARACTERS

MHL4HC:
	PUSH	AF	; SAVE A
	LD	A,H	; PRINT H
	CALL	MA2HC
	LD	A,L	; PRINT L
	CALL	MA2HC
	POP	AF	; RESTORE A
	RET

	END
