;
; SYSLIB Module Name:  SSPRINT
; Author:  Richard Conn
; SYSLIB Version Number:  3.6
; Module Version Number:  1.1

	public	sprint

;
;  SPRINT -- 
;	PRINT STRING PTED TO BY RET ADR UNTIL BINARY 0 ENCOUNTERED
;		TO CON: OR LST:
;	AFFECT NO REGISTERS OR FLAGS
;
	EXT	SPSTR

SPRINT:
	EX	(SP),HL	; HL=ADR, OLD HL ON STACK
	CALL	SPSTR	; PRINT STRING PTED TO BY HL
	EX	(SP),HL	; RESTORE HL AND NEW RET ADR
	RET

	END
