rem Build SYSLIB
zmac --rel --zmac syslib\S2FILEIO.Z80
zmac --rel --zmac syslib\S3FILEIO.Z80
zmac --rel --zmac syslib\SACAS1.Z80  
zmac --rel --zmac syslib\SACAS2.Z80  
zmac --rel --zmac syslib\SACAS3.Z80  
zmac --rel --zmac syslib\SAGO1.Z80   
zmac --rel --zmac syslib\SAGO2.Z80   
zmac --rel --zmac syslib\SAIF1.Z80   
zmac --rel --zmac syslib\SAIF2.Z80   
zmac --rel --zmac syslib\SALLOC.Z80  
zmac --rel --zmac syslib\SARGV.Z80   
zmac --rel --zmac syslib\SBBLINE.Z80 
zmac --rel --zmac syslib\SBDOS.Z80   
zmac --rel --zmac syslib\SBGO1.Z80   
zmac --rel --zmac syslib\SBGO2.Z80   
zmac --rel --zmac syslib\SBIN.Z80    
zmac --rel --zmac syslib\SBIOS.Z80   
zmac --rel --zmac syslib\SBIST.Z80   
zmac --rel --zmac syslib\SBLINE.Z80  
zmac --rel --zmac syslib\SBOUT.Z80   
zmac --rel --zmac syslib\SCAPIN.Z80  
zmac --rel --zmac syslib\SCAPS.Z80   
zmac --rel --zmac syslib\SCAPSTR.Z80 
zmac --rel --zmac syslib\SCATH.Z80   
zmac --rel --zmac syslib\SCCOUT.Z80  
zmac --rel --zmac syslib\SCIN.Z80    
zmac --rel --zmac syslib\SCLINE.Z80  
zmac --rel --zmac syslib\SCLOUT.Z80  
zmac --rel --zmac syslib\SCODEND.Z80 
zmac --rel --zmac syslib\SCOMP.Z80   
zmac --rel --zmac syslib\SCOMPHD.Z80 
zmac --rel --zmac syslib\SCONDIN.Z80 
zmac --rel --zmac syslib\SCOUT.Z80   
zmac --rel --zmac syslib\SCPOUT.Z80  
zmac --rel --zmac syslib\SCRC.Z80    
zmac --rel --zmac syslib\SCRC1.Z80   
zmac --rel --zmac syslib\SCRC2.Z80   
zmac --rel --zmac syslib\SCRLF.Z80   
zmac --rel --zmac syslib\SCST.Z80    
zmac --rel --zmac syslib\SDGO1.Z80   
zmac --rel --zmac syslib\SDGO2.Z80   
zmac --rel --zmac syslib\SDIR.Z80    
zmac --rel --zmac syslib\SDIR00.Z80  
zmac --rel --zmac syslib\SDIR01.Z80  
zmac --rel --zmac syslib\SDIR02.Z80  
zmac --rel --zmac syslib\SDIR03.Z80  
zmac --rel --zmac syslib\SDIR04.Z80  
zmac --rel --zmac syslib\SDIR05.Z80  
zmac --rel --zmac syslib\SDIR06.Z80  
zmac --rel --zmac syslib\SDIR07.Z80  
zmac --rel --zmac syslib\SDIR08.Z80  
zmac --rel --zmac syslib\SDIR09.Z80  
zmac --rel --zmac syslib\SDIR10.Z80  
zmac --rel --zmac syslib\SDIRBF.Z80  
zmac --rel --zmac syslib\SDIRQ.Z80   
zmac --rel --zmac syslib\SDIRQS.Z80  
zmac --rel --zmac syslib\SEN.Z80     
zmac --rel --zmac syslib\SEPRINT.Z80 
zmac --rel --zmac syslib\SEPSTR.Z80  
zmac --rel --zmac syslib\SEVAL.Z80   
zmac --rel --zmac syslib\SEVAL1.Z80  
zmac --rel --zmac syslib\SEVAL2.Z80  
zmac --rel --zmac syslib\SEVAL3.Z80  
zmac --rel --zmac syslib\SEVAL4.Z80  
zmac --rel --zmac syslib\SFAPPEND.Z80
zmac --rel --zmac syslib\SFCLOSE.Z80 
zmac --rel --zmac syslib\SFDELETE.Z80
zmac --rel --zmac syslib\SFEXIST.Z80 
zmac --rel --zmac syslib\SFILL.Z80   
zmac --rel --zmac syslib\SFMAKE.Z80  
zmac --rel --zmac syslib\SFNAME.Z80  
zmac --rel --zmac syslib\SFOPEN.Z80  
zmac --rel --zmac syslib\SFREAD.Z80  
zmac --rel --zmac syslib\SFRENAME.Z80
zmac --rel --zmac syslib\SFSIZE.Z80  
zmac --rel --zmac syslib\SFWRITE.Z80 
zmac --rel --zmac syslib\SFXIO.Z80   
zmac --rel --zmac syslib\SFYIO.Z80   
zmac --rel --zmac syslib\SGFA.Z80    
zmac --rel --zmac syslib\SGRR.Z80    
zmac --rel --zmac syslib\SGRR1.Z80   
zmac --rel --zmac syslib\SGUA.Z80    
zmac --rel --zmac syslib\SHCAS1.Z80  
zmac --rel --zmac syslib\SHCAS2.Z80  
zmac --rel --zmac syslib\SHCAS3.Z80  
zmac --rel --zmac syslib\SHDR.Z80    
zmac --rel --zmac syslib\SHGO1.Z80   
zmac --rel --zmac syslib\SHGO2.Z80   
zmac --rel --zmac syslib\SHIF1.Z80   
zmac --rel --zmac syslib\SHIF2.Z80   
zmac --rel --zmac syslib\SINITFCB.Z80
zmac --rel --zmac syslib\SINLINE.Z80 
zmac --rel --zmac syslib\SINSTR.Z80  
zmac --rel --zmac syslib\SISALNUM.Z80
zmac --rel --zmac syslib\SISALPHA.Z80
zmac --rel --zmac syslib\SISCTRL.Z80 
zmac --rel --zmac syslib\SISDIGIT.Z80
zmac --rel --zmac syslib\SISGRAPH.Z80
zmac --rel --zmac syslib\SISHEX.Z80  
zmac --rel --zmac syslib\SISPRINT.Z80
zmac --rel --zmac syslib\SISPUN.Z80  
zmac --rel --zmac syslib\SISSP.Z80   
zmac --rel --zmac syslib\SLA2HC.Z80  
zmac --rel --zmac syslib\SLADC.Z80   
zmac --rel --zmac syslib\SLAFDC.Z80  
zmac --rel --zmac syslib\SLCRLF.Z80  
zmac --rel --zmac syslib\SLFN1.Z80   
zmac --rel --zmac syslib\SLFN2.Z80   
zmac --rel --zmac syslib\SLFN3.Z80   
zmac --rel --zmac syslib\SLHL4HC.Z80 
zmac --rel --zmac syslib\SLHL5DC.Z80 
zmac --rel --zmac syslib\SLHLFDC.Z80 
zmac --rel --zmac syslib\SLOUT.Z80   
zmac --rel --zmac syslib\SLPRINT.Z80 
zmac --rel --zmac syslib\SLPSTR.Z80  
zmac --rel --zmac syslib\SLUCLOSE.Z80
zmac --rel --zmac syslib\SLUDIR.Z80  
zmac --rel --zmac syslib\SLUINIT.Z80 
zmac --rel --zmac syslib\SLUOPEN.Z80 
zmac --rel --zmac syslib\SMA2HC.Z80  
zmac --rel --zmac syslib\SMADC.Z80   
zmac --rel --zmac syslib\SMAFDC.Z80  
zmac --rel --zmac syslib\SMFN1.Z80   
zmac --rel --zmac syslib\SMFN2.Z80   
zmac --rel --zmac syslib\SMFN3.Z80   
zmac --rel --zmac syslib\SMHL4HC.Z80 
zmac --rel --zmac syslib\SMHL5DC.Z80 
zmac --rel --zmac syslib\SMHLFDC.Z80 
zmac --rel --zmac syslib\SMOVE.Z80   
zmac --rel --zmac syslib\SMTH01.Z80  
zmac --rel --zmac syslib\SMTH02.Z80  
zmac --rel --zmac syslib\SMTH03.Z80  
zmac --rel --zmac syslib\SMTH04.Z80  
zmac --rel --zmac syslib\SMTH05.Z80  
zmac --rel --zmac syslib\SMTH06.Z80  
zmac --rel --zmac syslib\SMTH07.Z80  
zmac --rel --zmac syslib\SMTH08.Z80  
zmac --rel --zmac syslib\SMTH09.Z80  
zmac --rel --zmac syslib\SMTH10.Z80  
zmac --rel --zmac syslib\SMTH11.Z80  
zmac --rel --zmac syslib\SMTH12.Z80  
zmac --rel --zmac syslib\SPA2HC.Z80  
zmac --rel --zmac syslib\SPADC.Z80   
zmac --rel --zmac syslib\SPAFDC.Z80  
zmac --rel --zmac syslib\SPAUSE.Z80  
zmac --rel --zmac syslib\SPFN1.Z80   
zmac --rel --zmac syslib\SPFN2.Z80   
zmac --rel --zmac syslib\SPFN3.Z80   
zmac --rel --zmac syslib\SPHL4HC.Z80 
zmac --rel --zmac syslib\SPHL5DC.Z80 
zmac --rel --zmac syslib\SPHLFDC.Z80 
zmac --rel --zmac syslib\SPOUT.Z80   
zmac --rel --zmac syslib\SPRINT.Z80  
zmac --rel --zmac syslib\SPSTR.Z80   
zmac --rel --zmac syslib\SRAND.Z80   
zmac --rel --zmac syslib\SRIN.Z80    
zmac --rel --zmac syslib\SRREAD.Z80  
zmac --rel --zmac syslib\SRWRITE.Z80 
zmac --rel --zmac syslib\SSA2HC.Z80  
zmac --rel --zmac syslib\SSADC.Z80   
zmac --rel --zmac syslib\SSAFDC.Z80  
zmac --rel --zmac syslib\SSCANNER.Z80
zmac --rel --zmac syslib\SSCFA.Z80   
zmac --rel --zmac syslib\SSCOUT.Z80  
zmac --rel --zmac syslib\SSCRLF.Z80  
zmac --rel --zmac syslib\SSCTLFL.Z80 
zmac --rel --zmac syslib\SSDMA.Z80   
zmac --rel --zmac syslib\SSFA.Z80    
zmac --rel --zmac syslib\SSFN1.Z80   
zmac --rel --zmac syslib\SSFN2.Z80   
zmac --rel --zmac syslib\SSFN3.Z80   
zmac --rel --zmac syslib\SSHL4HC.Z80 
zmac --rel --zmac syslib\SSHL5DC.Z80 
zmac --rel --zmac syslib\SSHLFDC.Z80 
zmac --rel --zmac syslib\SSKPUN.Z80  
zmac --rel --zmac syslib\SSKSP.Z80   
zmac --rel --zmac syslib\SSORT.Z80   
zmac --rel --zmac syslib\SSOUT.Z80   
zmac --rel --zmac syslib\SSPRINT.Z80 
zmac --rel --zmac syslib\SSPSTR.Z80  
zmac --rel --zmac syslib\SSUA.Z80    
zmac --rel --zmac syslib\SUD1.Z80    
zmac --rel --zmac syslib\SUD2.Z80    
rem todo check dupes
zmac --rel --zmac syslib\SLOUT.Z80
zmac --rel --zmac syslib\SBDOS.Z80
zmac --rel --zmac syslib\SFILEIO.Z80
zmac --rel --zmac syslib\S0FILEIO.Z80
zmac --rel --zmac syslib\S1FILEIO.Z80
rem Build C3LIB
zmac --rel --zmac c3lib\c3a2date.z80
zmac --rel --zmac c3lib\c3a2time.z80
zmac --rel --zmac c3lib\c3bios.z80
zmac --rel --zmac c3lib\c3brk.z80
zmac --rel --zmac c3lib\c3cmod.z80
zmac --rel --zmac c3lib\c3com.z80
zmac --rel --zmac c3lib\c3date2a.z80
zmac --rel --zmac c3lib\c3day.z80
zmac --rel --zmac c3lib\c3devc.z80
zmac --rel --zmac c3lib\c3devg.z80
zmac --rel --zmac c3lib\c3devl.z80
zmac --rel --zmac c3lib\c3dfmt.z80
zmac --rel --zmac c3lib\c3dini.z80
zmac --rel --zmac c3lib\c3dmy.z80
zmac --rel --zmac c3lib\c3dname.z80
zmac --rel --zmac c3lib\c3dosopt.z80
zmac --rel --zmac c3lib\c3dtbl.z80
zmac --rel --zmac c3lib\c3err.z80
zmac --rel --zmac c3lib\c3fbcd.z80
zmac --rel --zmac c3lib\c3gtime.z80
zmac --rel --zmac c3lib\c3int.z80
zmac --rel --zmac c3lib\c3opt.z80
zmac --rel --zmac c3lib\c3page.z80
zmac --rel --zmac c3lib\c3passwd.z80
zmac --rel --zmac c3lib\c3pmerr.z80
zmac --rel --zmac c3lib\c3pmin.z80
zmac --rel --zmac c3lib\c3pminit.z80
zmac --rel --zmac c3lib\c3pmout.z80
zmac --rel --zmac c3lib\c3pmpage.z80
zmac --rel --zmac c3lib\c3pmpb.z80
zmac --rel --zmac c3lib\c3pmpr.z80
zmac --rel --zmac c3lib\c3pmstat.z80
zmac --rel --zmac c3lib\c3pmstr.z80
zmac --rel --zmac c3lib\c3pmver.z80
zmac --rel --zmac c3lib\c3push.z80
zmac --rel --zmac c3lib\c3scbget.z80
zmac --rel --zmac c3lib\c3scbput.z80
zmac --rel --zmac c3lib\c3smin.z80
zmac --rel --zmac c3lib\c3stime.z80
zmac --rel --zmac c3lib\c3tbcd.z80
zmac --rel --zmac c3lib\c3time2a.z80
rem Build STRLIB
zmac --rel --zmac strlib\lexer.z80
zmac --rel --zmac strlib\strchr.z80
zmac --rel --zmac strlib\strlen.z80
zmac --rel --zmac strlib\tlookup.z80
zmac --rel --zmac strlib\token.z80
zmac --rel --zmac strlib\tokeng.z80
zmac --rel --zmac strlib\tokenl.z80
rem Build CFCB
rem Build NETLIB
zmac --rel --zmac netlib\nacsdrv.z80
zmac --rel --zmac netlib\ncfgtbl.z80
zmac --rel --zmac netlib\ndefpwd.z80
zmac --rel --zmac netlib\nerrmode.z80
zmac --rel --zmac netlib\nfredrv.z80
zmac --rel --zmac netlib\nlockrec.z80
zmac --rel --zmac netlib\nlogin.z80
zmac --rel --zmac netlib\nlogoff.z80
zmac --rel --zmac netlib\nnetstat.z80
zmac --rel --zmac netlib\nrcvmsg.z80
zmac --rel --zmac netlib\nscattr.z80
zmac --rel --zmac netlib\nscfgtbl.z80
zmac --rel --zmac netlib\nsendmsg.z80
zmac --rel --zmac netlib\nulckrec.z80

zmac --rel --zmac nendlist.z80
ld80 -o nendlist.hex -P100 -m -s nendlist.sym nendlist.rel SLOUT.REL SBDOS.REL
load <nendlist.hex >nendlist.com
ld80 -o nlogoff.hex -P100 -m -s nlogoff.sym nlogoff.rel SPRINTT.REL SBDOS.REL
load <nlogoff.hex >nlogoff.com
exit
